### PR TITLE
Fix rendering of gis

### PR DESCRIPTION
**Pull request by asprazz**
### Description

Please describe your pull request.

Fixes #

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by asprazz** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
I restarted the deployed, I need to fix this bug one day...
IMAP timeouts..

**Comment by asprazz** [comment]
i was just testing if bot works on other repos or not ? :)

**Comment by williamdes** [comment]
Oh, I did not even see that :laughing: 
It works everywhere ^^

**Comment by williamdes** [comment]
https://github.com/sudo-bot/gh-deployer

**Comment by williamdes** [comment]
seems like I should change the sub domain name naming because you could overwrite someone else's PR with a new repo

**Comment by asprazz** [comment]
> seems like I should change the sub domain name naming because you could overwrite someone else's PR with a new repo

Yeah that could be possible

**Pull request closed without merging**
